# Auto-generated by scripts/generate-pref-pane.py — 2026-03-14 19:59:07
# DO NOT EDIT MANUALLY.

pane-lacuna-title = Lacuna
lacuna-header = Lacuna Privacy Settings

category-lacuna =
    .tooltiptext = Lacuna Privacy & Security Settings

lacuna-browser-heading = Browser

lacuna-patch-browser-asrouter-enabled-checkbox =
    .label = Browser Asrouter
    .tooltiptext = Blocks ASRouter messaging campaigns, CFR recommendations, and What's New content from Mozilla servers. Default: True.

lacuna-patch-browser-newtab-enabled-checkbox =
    .label = Browser Newtab
    .tooltiptext = Disables Activity Stream pings and sponsored content fetching on the New Tab page. Default: True.

lacuna-patch-browser-region-enabled-checkbox =
    .label = Browser Region
    .tooltiptext = Prevents Firefox from auto-detecting your region via network requests. Region is hardcoded to US. Default: True.

lacuna-patch-browser-region-hardcoded-input-label = Browser Region Hardcoded
lacuna-patch-browser-region-hardcoded-input =
    .placeholder = patch.browser.region.hardcoded
    .tooltiptext = Controls patch.browser.region.hardcoded. Default: US.

lacuna-patch-browser-topsites-enabled-checkbox =
    .label = Browser Topsites
    .tooltiptext = Blocks Top Sites from fetching remote tile data and contile sponsored content. Default: True.

lacuna-patch-browser-urlbar-enabled-checkbox =
    .label = Browser Urlbar
    .tooltiptext = Disables URL bar network suggestions, Merino, and Firefox Suggest data collection. Default: True.

lacuna-patch-browser-taskbar-previews-favicon-network-checkbox =
    .label = Browser Taskbar Previews Favicon Network
    .tooltiptext = Blocks taskbar thumbnail previews from making network requests to fetch favicons. Default: True.

lacuna-extensions-heading = Extension Security

lacuna-patch-extensions-htmlaboutaddons-recommendations-enabled-checkbox =
    .label = Extensions Htmlaboutaddons Recommendations
    .tooltiptext = Blocks the about:addons Discovery API from fetching extension recommendations. Default: True.

lacuna-patch-extensions-blocklist-enabled-checkbox =
    .label = Extensions Blocklist
    .tooltiptext = Blocks remote MLBF (Bloom filter) blocklist updates. Extensions remain installable. Default: True.

lacuna-patch-extensions-locale-trigger-enabled-checkbox =
    .label = Extensions Locale Trigger
    .tooltiptext = Prevents locale change events from triggering automatic add-on update checks. Default: True.

lacuna-patch-extensions-systemaddon-enabled-checkbox =
    .label = Extensions Systemaddon
    .tooltiptext = Blocks automatic SystemAddon updates from Mozilla's server. Default: True.

lacuna-extensions-blocklist-enabled-input-label = Extension Blocklist (Native Switch)
lacuna-extensions-blocklist-enabled-input =
    .placeholder = extensions.blocklist.enabled
    .tooltiptext = Native Firefox blocklist switch. Disables the entire blocklist mechanism including remote MLBF updates.

lacuna-privacy-heading = Privacy Protection

lacuna-patch-privacy-font-echo-enabled-checkbox =
    .label = Privacy Font Echo
    .tooltiptext = Blocks font fingerprinting echo requests. Default: True.

lacuna-patch-privacy-urlformatter-enabled-checkbox =
    .label = Privacy Urlformatter
    .tooltiptext = Blocks URL template variables (%LOCALE%, %VERSION%, etc.) from leaking system info in network requests. Default: True.

lacuna-privacy-fingerprintingProtection-overrides-input-label = Fingerprinting Protection Overrides
lacuna-privacy-fingerprintingProtection-overrides-input =
    .placeholder = privacy.fingerprintingProtection.overrides
    .tooltiptext = Customize which FPP targets are enabled/disabled. Format: +AllTargets,-CSSPrefersColorScheme (string pref).

lacuna-media-heading = Media

lacuna-patch-media-gmp-enabled-checkbox =
    .label = Media Gmp
    .tooltiptext = Blocks OpenH264 and Widevine CDM update checks from GMP manager. Default: True.

lacuna-services-heading = Remote Settings

lacuna-patch-services-settings-fallback-enabled-checkbox =
    .label = Services Settings Fallback
    .tooltiptext = Forces RemoteSettings to use local fallback (cache + dump) instead of network. Default: True.

lacuna-patch-services-settings-enabled-checkbox =
    .label = Services Settings
    .tooltiptext = Blocks RemoteSettings from polling Mozilla's server. Uses local cache/dump fallback. Default: True.

lacuna-patch-services-settings-attachments-enabled-checkbox =
    .label = Services Settings Attachments
    .tooltiptext = Blocks RemoteSettings attachment downloads (e.g., fonts, ML models). Default: True.

lacuna-app-heading = App Updates

lacuna-patch-app-update-enabled-checkbox =
    .label = App Update
    .tooltiptext = Disables automatic Firefox application updates. Manual updates still work. Default: True.

lacuna-search-heading = Search

lacuna-patch-search-engines-enabled-checkbox =
    .label = Search Engines
    .tooltiptext = Filters search engines to only DDG as default, removing other pre-installed engines. Default: True.

lacuna-dom-heading = DOM

lacuna-patch-dom-sendbeacon-enabled-checkbox =
    .label = Dom Sendbeacon
    .tooltiptext = Blocks navigator.sendBeacon() API used for analytics/tracking pings. Default: True.
