/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */
//
// Auto-generated by scripts/generate-pref-pane.py — 2026-03-14 19:59:07

/* import-globals-from preferences.js */

Preferences.addAll([
  { id: "patch.browser.asrouter.enabled", type: "bool" },
  { id: "patch.browser.newtab.enabled", type: "bool" },
  { id: "patch.browser.region.enabled", type: "bool" },
  { id: "patch.browser.topsites.enabled", type: "bool" },
  { id: "patch.browser.urlbar.enabled", type: "bool" },
  { id: "patch.browser.taskbar.previews.favicon.network", type: "bool" },
  { id: "patch.extensions.htmlaboutaddons.recommendations.enabled", type: "bool" },
  { id: "patch.extensions.blocklist.enabled", type: "bool" },
  { id: "patch.extensions.locale_trigger.enabled", type: "bool" },
  { id: "patch.extensions.systemaddon.enabled", type: "bool" },
  { id: "patch.privacy.font.echo.enabled", type: "bool" },
  { id: "patch.privacy.urlformatter.enabled", type: "bool" },
  { id: "patch.media.gmp.enabled", type: "bool" },
  { id: "patch.services.settings.fallback.enabled", type: "bool" },
  { id: "patch.services.settings.enabled", type: "bool" },
  { id: "patch.services.settings.attachments.enabled", type: "bool" },
  { id: "patch.app.update.enabled", type: "bool" },
  { id: "patch.search.engines.enabled", type: "bool" },
  { id: "patch.dom.sendbeacon.enabled", type: "bool" },
  { id: "patch.browser.region.hardcoded", type: "string" },
  { id: "extensions.blocklist.enabled", type: "string" },
  { id: "privacy.fingerprintingProtection.overrides", type: "string" },
]);

var gLacunaPane = {
  _pane: null,

  init() {
    // Checkboxes use XHTML preference="" attribute for automatic
    // two-way binding. No manual sync listeners needed.
  },
};
