#!/usr/bin/env python3
"""
Generate prefs-template.js from all *prefs.json files,
then copy to firefox-esr obj-*/dist/bin/.

Usage:
    python3 scripts/generate_prefs.py          # generate + copy
    python3 scripts/generate_prefs.py --dry    # generate only, no copy
"""

import json
import shutil
import sys
from collections import OrderedDict
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PATCH_DIR = Path(__file__).parent.parent
LACUNA_DIR = PATCH_DIR.parent
OUTPUT_FILE = PATCH_DIR / "100-custom" / "prefs-template.js"
FIREFOX_REPOS = [LACUNA_DIR / "firefox-esr"]

EXCLUDE_DIRS = {".cleanup", ".backup"}


# ---------------------------------------------------------------------------
# Stage 1: Collect prefs from JSON
# ---------------------------------------------------------------------------

def normalize_pref(value):
    """Normalize pref value: dict with {value, description} or plain value."""
    if isinstance(value, dict) and "value" in value:
        return value["value"]
    return value


def load_prefs_files():
    """Load all *prefs.json, return OrderedDict of source_name -> info."""
    sources = OrderedDict()
    files = sorted(
        f for f in PATCH_DIR.glob("**/*prefs.json")
        if not EXCLUDE_DIRS & set(f.parts)
    )
    for path in files:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception as e:
            print(f"  ERROR reading {path}: {e}")
            continue
        raw_prefs = data.get("preferences", {})
        if not raw_prefs:
            continue
        # Normalize: extract value from dict entries
        prefs = {k: normalize_pref(v) for k, v in raw_prefs.items()}
        sources[path.stem] = {
            "file": str(path.relative_to(PATCH_DIR)),
            "description": data.get("description", ""),
            "category": data.get("category", ""),
            "preferences": prefs,
        }
    return sources


def find_duplicates(sources):
    """Detect prefs defined in multiple files."""
    seen = {}
    for info in sources.values():
        for key in info["preferences"]:
            seen.setdefault(key, []).append(info["file"])
    dupes = {k: v for k, v in seen.items() if len(v) > 1}
    if dupes:
        print("  WARNING: Duplicate preferences:")
        for pref, files in dupes.items():
            print(f"    '{pref}' in: {', '.join(files)}")
    return dupes


# ---------------------------------------------------------------------------
# Stage 2: Generate prefs-template.js
# ---------------------------------------------------------------------------

def format_value(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, (int, float)):
        return str(value)
    return f'"{value}"'


def group_by_category(sources):
    """Group sources by category, preserving order."""
    categories = OrderedDict()
    for name, info in sources.items():
        cat = info.get("category", "other")
        categories.setdefault(cat, []).append((name, info))
    return categories


def render_template(sources):
    """Render prefs-template.js content."""
    lines = [
        "// Lacuna Prefs Template",
        f"// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "// Auto-generated by scripts/generate_prefs.py",
        "",
        'user_pref("patch.lacuna.prefs.loaded", true);',
        "",
    ]

    for cat, cat_sources in group_by_category(sources).items():
        lines.append("// " + "=" * 72)
        lines.append(f"// === {cat.upper()} ===")
        lines.append("// " + "=" * 72)
        lines.append("")

        for _, info in cat_sources:
            lines.append(f"// Source: {info['file']}")
            if info["description"]:
                lines.append(f"// Description: {info['description']}")
            lines.append("")

            prefs = info["preferences"]
            patch = OrderedDict((k, v) for k, v in sorted(prefs.items()) if k.startswith("patch."))
            other = OrderedDict((k, v) for k, v in sorted(prefs.items()) if not k.startswith("patch."))

            if patch:
                lines.append("// Patch control switches")
                for k, v in patch.items():
                    lines.append(f'user_pref("{k}", {format_value(v)});')
                lines.append("")

            if other:
                if patch:
                    lines.append("// Configuration values")
                for k, v in other.items():
                    lines.append(f'user_pref("{k}", {format_value(v)});')
                lines.append("")

    lines.append("// " + "=" * 72)
    lines.append("// === END OF LACUNA PREFS ===")
    lines.append("// " + "=" * 72)
    return "\n".join(lines)


def write_template(content):
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(content, encoding="utf-8")


# ---------------------------------------------------------------------------
# Stage 3: Copy to build output
# ---------------------------------------------------------------------------

def copy_to_builds():
    """Copy prefs-template.js and extensions to obj-*/dist/bin/ in each repo."""
    if not OUTPUT_FILE.exists():
        print("  ERROR: prefs-template.js not found")
        return False

    copied = 0
    ext_src = PATCH_DIR / "200-ui" / "distribution" / "extensions"

    for repo in FIREFOX_REPOS:
        if not repo.exists():
            continue
        for obj_dir in repo.glob("obj-*"):
            bin_dir = obj_dir / "dist" / "bin"
            bin_dir.mkdir(parents=True, exist_ok=True)
            target = bin_dir / "prefs-template.js"
            shutil.copy2(OUTPUT_FILE, target)
            print(f"  {repo.name}/{target.relative_to(repo)}")
            copied += 1

            # Copy bundled extensions
            if ext_src.is_dir():
                ext_dst = bin_dir / "distribution" / "extensions"
                ext_dst.mkdir(parents=True, exist_ok=True)
                for xpi in sorted(ext_src.glob("*.xpi")):
                    shutil.copy2(xpi, ext_dst / xpi.name)
                    print(f"  {repo.name}/{(ext_dst / xpi.name).relative_to(repo)}")
                    copied += 1

    if not copied:
        print("  No obj-* found (build Firefox first)")
    return copied > 0


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    dry = "--dry" in sys.argv

    print("--- Generate prefs-template.js ---")
    sources = load_prefs_files()
    find_duplicates(sources)

    total = sum(len(s["preferences"]) for s in sources.values())
    patch_count = sum(
        sum(1 for k in s["preferences"] if k.startswith("patch."))
        for s in sources.values()
    )
    print(f"  {len(sources)} files, {total} prefs ({patch_count} patch.*)")

    content = render_template(sources)
    write_template(content)
    print(f"  -> {OUTPUT_FILE.relative_to(LACUNA_DIR)} ({len(content.splitlines())} lines)")

    if not dry:
        print("")
        print("--- Copy to builds ---")
        copy_to_builds()

    print("")
    print(f"Done: {total} prefs, {patch_count} patch.*")


if __name__ == "__main__":
    main()
